CREATE TABLE IF NOT EXISTS `visitors` (
  `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
  `ip_address` VARCHAR(50) NOT NULL,
  `user_agent` TEXT NOT NULL,
  `unique_id` VARCHAR(100) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
